[package]
name = "cqrs-proptest"
version = "0.3.0"
authors = ["Marcus Griep <marcus@griep.us>"]
description = "Property testing utilities for cqrs"
license = "Apache-2.0"
readme = "../README.md"
documentation = "https://docs.rs/cqrs-proptest"
repository = "https://github.com/cq-rs/cqrs"
edition = "2018"

[dependencies]
cqrs-core = { version = "0.2.1", path = "../cqrs-core" }
proptest = "0.9"

[dev-dependencies]
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"

[badges]
travis-ci = { repository = "cq-rs/cqrs", branch = "master" }
